-------------------------------------------------------------------------------
Test set: org.apache.logging.log4j.spi.DefaultThreadContextStack_ESTest
-------------------------------------------------------------------------------
Tests run: 50, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.018 s <<< FAILURE! -- in org.apache.logging.log4j.spi.DefaultThreadContextStack_ESTest
org.apache.logging.log4j.spi.DefaultThreadContextStack_ESTest.test20 -- Time elapsed: 0.012 s <<< FAILURE!
java.lang.AssertionError: Exception was not thrown in org.apache.logging.log4j.spi.MutableThreadContextStack but in org.apache.logging.log4j.spi.DefaultThreadContextStack.formatTo(DefaultThreadContextStack.java:289): java.lang.NullPointerException
	at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:111)
	at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:48)
	at org.apache.logging.log4j.spi.DefaultThreadContextStack_ESTest.test20(DefaultThreadContextStack_ESTest.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

